# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bncparse',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/bncparse',
                'lib_path': 'bncparse'},
  'syms': {'bncparse.core': {'bncparse.core.get_xml': ('core.html#get_xml', 'bncparse/core.py')}}}