# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['get_xml']

# %% ../nbs/00_core.ipynb 5
from pathlib import Path

from lxml import etree

# %% ../nbs/00_core.ipynb 13
def get_xml(f_path):
    with open(f_path, 'r') as f:
        f = f.read()
    xml = etree.fromstring(f)
    return xml
